### PR TITLE
Upgrade react-ga4 in order to also support Google Analytics GA4

### PR DESCRIPTION
**Pull request by avoinea**
- refs #9

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh Will this cause any problem for our projects? I am not sure if we have some that are using Google Analytics. If we do, they need to be updated to GA4 anyway, because Google is deprecating the old one.

**Comment by avoinea** [comment]
@davisagli react-ga4 should also work with `UA-`. See https://github.com/react-ga/react-ga/issues/493#issuecomment-865316243

**Comment by davisagli** [comment]
@avoinea ah, so it is a different library that adds support for GA4 but does not remove support for old Analytics. Cool.

**Comment by avoinea** [comment]
@davisagli In theory :smile: Please test it first with `UA-`. I only have GA4

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@avoinea I just saw the PR :( sorry, could you update it to add a towncrier news item? I can release afterwards. Thanks! Make sure you update the lock too!

**Comment by avoinea** [comment]
@sneridagh Ski vacation here. Will do next week if no one will take it until then 😉

**Comment by steffenri** [comment]
@avoinea What's the status here? Would be great to have this released soon! :)

**Comment by sneridagh** [comment]
@avoinea ping me if you want to move things forward with this one!

**Comment by avoinea** [comment]
@sneridagh I fixed the PR, added changelog. 

You should consider upgrading to **react-ga4 2.1.0** https://www.npmjs.com/package/react-ga4

**Comment by sneridagh** [comment]
@avoinea thanks!

**Pull request merged**
